/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fx_qtkeyboard_QTKeyBoardJNI */

#ifndef _Included_com_fx_qtkeyboard_QTKeyBoardJNI
#define _Included_com_fx_qtkeyboard_QTKeyBoardJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fx_qtkeyboard_QTKeyBoardJNI
 * Method:    KeyBoardInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fx_qtkeyboard_QTKeyBoardJNI_KeyBoardInit
  (JNIEnv *, jclass);

/*
 * Class:     com_fx_qtkeyboard_QTKeyBoardJNI
 * Method:    KeyBoardOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fx_qtkeyboard_QTKeyBoardJNI_KeyBoardOpen
  (JNIEnv *, jclass);

/*
 * Class:     com_fx_qtkeyboard_QTKeyBoardJNI
 * Method:    KeyBoardClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fx_qtkeyboard_QTKeyBoardJNI_KeyBoardClose
  (JNIEnv *, jclass);

/*
 * Class:     com_fx_qtkeyboard_QTKeyBoardJNI
 * Method:    Release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fx_qtkeyboard_QTKeyBoardJNI_Release
  (JNIEnv *, jclass);

/*
 * Class:     com_fx_qtkeyboard_QTKeyBoardJNI
 * Method:    Test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fx_qtkeyboard_QTKeyBoardJNI_Test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
